### ISSUE TITLE
Upgrade to latest version of dcraw

### ISSUE THREAD

**Issue by ffosselle** [ImageMagick/dcraw#2]
Would it be possible to upgrade to the latest version of dcraw?

Version 9.28 has been released a year ago. Additional camera models have been added, for example the Canon EOS D5 Mark IV:

http://www.cybercom.net/~dcoffin/dcraw/archive/

![image](https://user-images.githubusercontent.com/1826475/51939688-612e1f00-2410-11e9-8178-5f722e717a5b.png)

**Comment by dlemstra** [comment]
Thanks for reminding us to upgrade it. We made some changes to the code including adding support for OpenCL so it won't be an easy upgrade. Might take a while before we have time to resolve this.

**Comment by dlemstra** [comment]
The upgrade has been done.
