### ISSUE TITLE
Trouble when CFAPattern is not 2 1 1 0

### ISSUE THREAD

**Issue by SebastianoGuer** [ImageMagick/dcraw#5]
When CFAPattern is different from 2 1 1 0, in my case is 1 0 2 1, the openCL kernel subroutine fails to interpolate the DNG image. This is due to the fact that x (height) and y (width) picture coordinates are inverted in openCL computing with respect to cpu computing.
So, when calling FC macro in the openCL kernel subroutine, the row is inverted with column, and the interpolation brings to wrong results.

**Comment by dlemstra** [comment]
It sounds like you know the exact spot where a change should be made? Feel free to open a PR or tell us the exact spot where we should make a change?

**Comment by SebastianoGuer** [comment]
The most simpy correction is to invert, in the two FC macro calls of ahd_interpolateK, the arguments (i. e. row with column). More significant change would be to invert the "ascissa" (x) references with "ordinata" (y) references, leaving FC macro arguments unchanged…
________________________________

**Comment by SebastianoGuer** [comment]
I must correct the previous message; the inverting of the "ordinate" with "abscissa" is only a formal change to render the code more clear.
The FC arguments should be anyway inverted.

Da: Dirk Lemstra ***@***.***>
Inviato: venerdì 7 aprile 2023 17:35
A: ImageMagick/dcraw ***@***.***>
Cc: Nello ***@***.***>; Author ***@***.***>
Oggetto: Re: [ImageMagick/dcraw] Trouble when CFAPattern is not 2 1 1 0 (Issue #5)


It sounds like you know the exact spot where a change should be made? Feel free to open a PR or tell us the exact spot where we should make a change?

-

**Comment by SebastianoGuer** [comment]
Finally, what I propose, without any change more, is:
int fc = FC(xx - left, yy - top);
becomes
int fc = FC(yy - top, xx - left);
and
int fc = FC(x, y);
becomes
int fc = FC(y, x);
More clear should be to invert the 'x' identifiers with 'y', but "-top" and "-left" must remain first and second.

Da: Dirk Lemstra ***@***.***>
Inviato: venerdì 7 aprile 2023 17:35
A: ImageMagick/dcraw ***@***.***>
Cc: Nello ***@***.***>; Author ***@***.***>
Oggetto: Re: [ImageMagick/dcraw] Trouble when CFAPattern is not 2 1 1 0 (Issue #5)


It sounds like you know the exact spot where a change should be made? Feel free to open a PR or tell us the exact spot where we should make a change?

-

**Comment by dlemstra** [comment]
We have applied the changes you suggested. But I had to add another change. You can find the changes that were made in the commit that is referenced in this issue.

**Comment by SebastianoGuer** [comment]
Thanks.
